name: row3yourboat

services:
  proxy-server:
    build: ./proxy-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - mitmproxy_cert:/root/.mitmproxy
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"

  db:
    image: postgres:17
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 1s
      timeout: 1s
      retries: 3

volumes:
  db_data:
  mitmproxy_cert:
