name: rrryb

services:
  proxy-server:
    build: ./proxy-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - mitmproxy_cert:/root/.mitmproxy
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"

  db:
    image: postgres:17
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 1s
      timeout: 1s
      retries: 3

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      # - frontend
      - backend

volumes:
  db_data:
  mitmproxy_cert:
  influxdb_data:
  grafana_data: