{
 "title": "Row Row Row Your Boat",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "User",
    "query": {
     "query": "from(bucket: \"rrryb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"user_traffic\")\n  |> group()\n  |> keep(columns: [\"username\"])\n  |> distinct(column: \"username\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Download Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrryb\")\n  |> range(start: -30s)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> filter(fn: (r) => r._field == \"download_bytes\")\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with\n      _value: r._value / 30\n  }))"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrryb\")\n  |> range(start: -30s)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> filter(fn: (r) => r._field == \"upload_bytes\")\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with\n      _value: r._value / 30\n  }))"
    }
   ]
  },
  {
   "title": "Online Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrryb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"user_traffic\")\n  |> group()\n  |> keep(columns: [\"username\"])\n  |> distinct(column: \"username\")\n  |> count()"
    }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"rrryb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"user_traffic\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> map(fn: (r) => ({\n      r with\n      _value: if r._field == \"upload_bytes\" then -1 * r._value else r._value\n  }))\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> map(fn: (r) => ({\n      r with\n      _field: if r._field == \"download_bytes\" then \"Download\" else \n        if r._field == \"upload_bytes\" then \"Upload\" else \n        r._field,\n      _value: r._value / 60\n  }))"
    }
   ]
  },
  {
   "title": "Online User",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"rrryb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"user_traffic\")\n  |> filter(fn: (r) => r._field == \"download_bytes\" or r._field == \"upload_bytes\")\n  |> group(columns: [\"username\", \"_field\"])\n  |> sum()\n  |> pivot(\n    rowKey: [\"username\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> map(fn: (r) => ({\n    user: r.username,\n    download_bytes: r.download_bytes,\n    upload_bytes: r.upload_bytes\n  }))"
    }
   ]
  },
  {
   "title": "User Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"rrryb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"user_traffic\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"username\"])\n  |> filter(fn: (r) => r.username == \"${User}\")\n  |> map(fn: (r) => ({\n      r with\n      _value: if r._field == \"upload_bytes\" then -1 * r._value else r._value\n  }))\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> map(fn: (r) => ({\n      r with\n      _field: if r._field == \"download_bytes\" then \"Download\" else \n        if r._field == \"upload_bytes\" then \"Upload\" else \n        r._field,\n      _value: r._value / 60\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n"
    }
   ]
  }
 ]
}